server:
  port: 8888
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/bbt_db
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/


#logging:
#  level:
mybatis:
  typeAliasesPackage: com.bbtong.Pojo,com.bbtong.Util
#    com.bbt.Dao: debug

debug: true

